name: Rebase feature branch with main

on:
  push:
    branches:
      - main

permissions: write-all

env:
  BRANCH_TO_REBASE: feature

jobs:
  rebase-latest-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase branch
        run: |
          git fetch origin
          git checkout ${{ env.BRANCH_TO_REBASE }}
          git pull origin ${{ env.BRANCH_TO_REBASE }}
          git rebase origin/main
          git push origin ${{ env.BRANCH_TO_REBASE }} --force-with-lease
