name: Rebase Feature Branch

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 15 * * *"

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest changes in main branch
        run: git fetch origin main

      - name: Checkout feature branch
        run: git checkout feature

      - name: Rebase feature onto main
        run: git rebase origin/main

      - name: Push changes
        run: git push origin feature --force-with-lease
